# Generated by Django 5.0.6 on 2024-07-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nis', models.CharField(max_length=10, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('tanggal_lahir', models.DateField()),
            ],
        ),
    ]
